### ISSUE TITLE
errors while trying to run the build

### ISSUE THREAD

**Issue by vitamon** [closureplease/todoAppMantri#1]
> grunt deps
Running "mantriDeps:todoApp" (mantriDeps) task
>> Error: Command failed: python /Users/tva/work/mantri-test/todoAppMantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/depswriter.py  --root_with_prefix="js js" --output_file=./deps.js
>> python: can't open file '/Users/rva/work/mantri-test/todoAppMantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/depswriter.py': [Errno 2] No such file or directory
>> FAILED to run command for target: todoApp
Warning: Task "mantriDeps:todoApp" failed. Use --force to continue.

> grunt build
Running "mantriBuild:todoApp" (mantriBuild) task
debug :: Passed Validations.
debug :: Created temp dir and google mock: /var/folders/47/lwjx26l905vgxmn0r9qq1s6w00cwyp/T/1522853368365.919
debug :: Starting itterating on vendor libs...
debug :: Builder command constructed. Executing...
Executing: python /Users/tva/work/mantri-test/todoAppMantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/closurebuilder.py  -i js/app.js --root=js/ --root=/Users/tva/work/mantri-test/todoAppMantri/node_modules/mantri/closure-mock -o list
>> Error: Command failed: python /Users/tva/work/mantri-test/todoAppMantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/closurebuilder.py  -i js/app.js --root=js/ --root=/Users/tva/work/mantri-test/todoAppMantri/node_modules/mantri/closure-mock -o list
>> python: can't open file '/Users/tva/work/mantri-test/todoAppMantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/closurebuilder.py': [Errno 2] No such file or directory

>mantri deps --debug
Starting dependency task...
Executing: python /Users/tva/work/mantri-test/todoAppMantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/depswriter.py  --root_with_prefix="./ ./" --output_file=deps.js
>> Error: Command failed: python /Users/tva/work/mantri-test/todoAppMantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/depswriter.py  --root_with_prefix="./ ./" --output_file=deps.js
>> python: can't open file '/Users/tva/work/mantri-test/todoAppMantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/depswriter.py': [Errno 2] No such file or directory
>> FAILED to run command for target: cli

**Comment by thanpolas** [comment]
Hey @vitamon, I have not touched this project for 5 years now and as [I state in the main repo README ](https://github.com/thanpolas/mantri#warning-not-maintained) this project is no longer active.

Thank you for the consideration
